### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/gatsby-loveria#146]
Only use one H1 per page; add SEO-appropriate H2s
Add sitemap (see global.kfc.com for one that Leoman did)
Add robots.txt (see global.kfc.com for one that Leoman did)
Add Schema to site
Add `rel="noopener"` or `rel="noreferrer" for Instagram and Facebook links
Add alt tags to all images
Google Analytics not loading: (UA-79786751-63)
Do not use duplicate meta descriptions - be creative
Fix 404 chandonarbors.com
Fix 429 fortworthbusiness.com
Improve page titles with SEO
Add Expires headers
Preload key requests (fonts)
Minify javascript

**Comment by karen-simplemedia** [comment]
Issues fixed. 

These items are not currently actionable and still need info:
- Add Schema to site
- Do not use duplicate meta descriptions - be creative
- Improve page titles with SEO
